#server
server:
  port: 9001

#spring
spring:
  application:
    name: lagou-cloud-gateway
  cloud:
    #网关
    gateway:
      #路由
      routes:
        #订单
        - id: lagou-service-order-router  # (唯一就好)
          uri: lb://lagou-service-order   #动态路由: 从注册中心获取对应服务的实例
          predicates:                     #断言: 断言成功后, 交给某个微服务处理是通过转发
            - Path=/order/**              #order开头的请求, 交给lb://lagou-service-order
        #商品
        - id: lagou-service-goods-router
          uri: lb://lagou-service-goods
          predicates:
            - Path=/goods/**


#注册中心
eureka:
  instance:
    prefer-ip-address: true       #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@  #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    lease-renewal-interval-in-seconds: 30     #租约续约间隔时间，默认30秒
    lease-expiration-duration-in-seconds: 90  #租约到期，默认值90秒, EurekaServer会将服务从列表移除
  client:
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:9300/eureka,http://LagouCloudEurekaServerB:9301/eureka
    register-with-eureka: true          #向Eureka中心注册自己的信息 (默认为true)
    fetch-registry: true                #从Eureka Server获取服务信息 (默认为true)
    registry-fetch-interval-seconds: 30 #每隔多久拉取一次服务列表