#定义自己
server:
  port: 9300

#spring
spring:
  application:
    name: lagou-cloud-eureka

#eureka
eureka:
  instance:
    prefer-ip-address: true       #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@ #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
  client:
    service-url:                  #eureka server 地址
      defaultZone: http://LagouCloudEurekaServerB:9301/eureka #http://LagouCloudEurekaServerB:9301/eureka,http://LagouCloudEurekaServerC:9302/eureka
    register-with-eureka: true    #向Eureka中心注册自己的信息 (默认为true)
    fetch-registry: true          #从Eureka Server获取服务信息 (默认为true)
  server:
    enable-self-preservation: false  #关闭自我保护模式（默认为打开,建议生产环境打开自我保护机制）