server:
  port: 9400

eureka:
  client:
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:9300/eureka,http://LagouCloudEurekaServerB:9301/eureka
    register-with-eureka: true          #向Eureka中心注册自己的信息 (默认为true)
    fetch-registry: true                #从Eureka Server获取服务信息 (默认为true)
    registry-fetch-interval-seconds: 30 #每隔多久拉取一次服务列表
  instance:
    prefer-ip-address: true       #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@  #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    lease-renewal-interval-in-seconds: 30     #租约续约间隔时间，默认30秒
    lease-expiration-duration-in-seconds: 90  #租约到期，默认值90秒

spring:
  application:
    name: lagou-cloud-config
  cloud:
    config:
      server:
        #git
        git:
          uri: https://github.com/kimyundung/lagou-config.git #git地址
          username: kimyundung
          password: ********
          search-paths:  #加载的项目(可多个)
            - lagou-config
      label: master #分支
  rabbitmq:
    host: 192.168.8.128
    port: 5672
    username: kim
    password: 123123

#建议暴露所有的端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true
