#server
server:
  port: 9201    #当前应用访问端口

#spring
spring:
  application:
    name: lagou-service-goods     #项目名称(微服务中唯一标识)
  datasource:                     #数据源信息
    url: jdbc:mysql://localhost:3306/lagou?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #post请求全局日期转换(未验证)
    time-zone: GMT+8

#分页查询
pagehelper:
  helper-dialect: mysql     #方言

#映射配置文件
mybatis:
  mapper-locations: classpath:com/lagou/goods/mapper/*.xml  #配置MyBatis的xml配置文件路径
  type-aliases-package: com.lagou.common                    #配置XML映射文件中指定的实体类别名路径
  configuration:
    map-underscore-to-camel-case: true                      #驼峰命名

#eureka
eureka:
  instance:
    prefer-ip-address: true       #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@ #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    lease-renewal-interval-in-seconds: 30     #租约续约间隔时间，默认30秒
    lease-expiration-duration-in-seconds: 90  #租约到期，服务有效时间，默认值90秒,服务超过90秒没有发生心跳，EurekaServer会将服务从列表移除
  client:
    service-url:                        #eureka server 地址
      defaultZone: http://LagouCloudEurekaServerA:9300/eureka,http://LagouCloudEurekaServerB:9301/eureka
    register-with-eureka: true          #向Eureka中心注册自己的信息 (默认为true)
    fetch-registry: true                #从Eureka Server获取服务信息 (默认为true)
    registry-fetch-interval-seconds: 30 # 每隔多久拉取一次服务列表